name: CloseArithmetic

on:
  workflow_dispatch:

jobs:
  prove:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install runtime dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgmp-dev unzip wget

      - name: Download TLAPS bundle (with Isabelle)
        run: |
          mkdir -p /opt/tlaps
          wget https://github.com/tlaplus/tlapm/releases/download/v1.5.2/tlaps-1.5.2-linux.zip
          unzip -q tlaps-1.5.2-linux.zip -d /opt/tlaps
          /opt/tlaps/tlaps-1.5.2/bin/tlapm --version
          /opt/tlaps/tlaps-1.5.2/bin/isabelle version

      - name: Build ArithmeticIsa Isabelle image
        run: |
          export PATH="/opt/tlaps/tlaps-1.5.2/bin:$PATH"
          cd proofs
          isabelle build -d . -b ArithmeticIsa

      - name: Configure TLAPS to use Isabelle image
        run: |
          cat > proofs/tlaps-ci.cfg <<'CFG'
          [prover]
          timeout = 60

          [isabelle]
          enabled = true
          image = ArithmeticIsa
          CFG
          cat proofs/tlaps-ci.cfg

      - name: Prepare log directory
        run: mkdir -p verification_logs

      - name: Run TLAPS on safety modules
        run: |
          export PATH="/opt/tlaps/tlaps-1.5.2/bin:$PATH"
          export TLA_PATH="$(pwd)/tla:$(pwd)/proofs"
          CFG="$(pwd)/proofs/tlaps-ci.cfg"
          for mod in QuorumIntersection CertificateUniqueness FinalizationSafety; do
            echo "===== $mod ====="
            tlapm -C "$CFG" "proofs/${mod}.tla" \
              2>&1 | tee "verification_logs/tlaps_${mod,,}_ci.log"
          done

      - name: Summarise TLAPS results
        run: |
          for f in verification_logs/tlaps_*_ci.log; do
            echo "======== $f ========"
            tail -n 10 "$f"
          done

      - name: Upload proof artefacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: closed-proofs
          path: |
            proofs/.tlacache/
            proofs/*/*.proof
            verification_logs/tlaps_*_ci.log
            proofs/tlaps-ci.cfg
          retention-days: 30
