name: CloseArithmetic

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/close_arithmetic.yaml'
      - 'proofs/**'
      - 'tla/**'
  workflow_dispatch:

jobs:
  prove:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and install TLAPS 1.6.0-pre
        run: |
          cd /tmp
          wget https://github.com/tlaplus/tlapm/releases/download/1.6.0-pre/tlapm-1.6.0-pre-x86_64-linux-gnu.tar.gz
          tar -xzf tlapm-1.6.0-pre-x86_64-linux-gnu.tar.gz
          sudo mv tlapm /usr/local/
          sudo ln -sf /usr/local/tlapm/bin/tlapm /usr/local/bin/tlapm
          tlapm --version

      - name: Download and install Isabelle 2025
        run: |
          cd /tmp
          # Try multiple mirrors
          wget --no-check-certificate https://isabelle.in.tum.de/website-Isabelle2025/dist/Isabelle2025_linux.tar.gz 2>/dev/null || \
          curl -L -k -o Isabelle2025_linux.tar.gz https://isabelle.in.tum.de/website-Isabelle2025/dist/Isabelle2025_linux.tar.gz 2>/dev/null || \
          wget http://mirror.cse.unsw.edu.au/pub/isabelle/release/Isabelle2025_linux.tar.gz 2>/dev/null || \
          curl -L -o Isabelle2025_linux.tar.gz http://mirror.cse.unsw.edu.au/pub/isabelle/release/Isabelle2025_linux.tar.gz

          tar -xzf Isabelle2025_linux.tar.gz
          sudo mv Isabelle2025 /usr/local/tlapm/Isabelle
          sudo ln -sf /usr/local/tlapm/Isabelle/bin/isabelle /usr/local/bin/isabelle
          isabelle version

      - name: Build ArithmeticIsa image
        run: |
          export ISABELLE_HOME=/usr/local/tlapm/Isabelle
          export PATH="/usr/local/tlapm/Isabelle/bin:$PATH"
          cd proofs
          isabelle build -d . -b ArithmeticIsa

      - name: Write TLAPS config that uses the image
        run: |
          cd proofs
          cat > tlaps-ci.cfg <<'EOF'
          [prover]
          timeout = 60

          [isabelle]
          enabled = true
          image = ArithmeticIsa
          EOF

      - name: Create log directory
        run: mkdir -p verification_logs

      - name: Run TLAPS on all three safety modules
        run: |
          export TLA_PATH="$(pwd)/tla:$(pwd)/proofs"
          export ISABELLE_HOME=/usr/local/tlapm/Isabelle
          export PATH="/usr/local/tlapm/Isabelle/bin:$PATH"
          for mod in QuorumIntersection CertificateUniqueness FinalizationSafety; do
            echo "===== $mod ====="
            tlapm -C proofs/tlaps-ci.cfg "proofs/${mod}.tla" \
              2>&1 | tee "verification_logs/tlaps_${mod,,}_ci.log"
          done

      - name: Summarise results
        run: |
          for f in verification_logs/tlaps_*_ci.log; do
            echo "======== $f ========"
            tail -n 10 "$f"
          done

      - name: Upload closed-proof artefacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: closed-proofs
          path: |
            proofs/.tlacache/
            proofs/*/*.proof
            verification_logs/tlaps_*_ci.log
            proofs/tlaps-ci.cfg
          retention-days: 30
