name: CloseArithmetic

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  prove:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download TLAPS 1.6.0-pre
        run: |
          wget https://github.com/tlaplus/tlapm/releases/download/1.6.0-pre/tlapm-1.6.0-pre-x86_64-linux-gnu.tar.gz
          tar -xzf tlapm-1.6.0-pre-x86_64-linux-gnu.tar.gz
          sudo mv tlapm /usr/local/tlapm
          echo "/usr/local/tlapm/bin" >> $GITHUB_PATH

      - name: Download Isabelle 2025
        run: |
          wget https://www.cl.cam.ac.uk/research/hvg/Isabelle/dist/Isabelle2025_linux.tar.gz
          tar -xzf Isabelle2025_linux.tar.gz
          sudo mv Isabelle2025 /usr/local/Isabelle
          echo "ISABELLE_HOME=/usr/local/Isabelle" >> $GITHUB_ENV
          echo "/usr/local/Isabelle/bin" >> $GITHUB_PATH

      - name: Verify installations
        run: |
          tlapm --version
          isabelle version

      - name: Build ArithmeticIsa
        run: |
          cd proofs
          isabelle build -d . -b -v ArithmeticIsa

      - name: Create config and logs directory
        run: |
          mkdir -p verification_logs
          cat > tlaps-ci.cfg <<'EOF'
          [prover]
          timeout = 60

          [isabelle]
          enabled = true
          image = ArithmeticIsa
          EOF

      - name: Prove QuorumIntersection
        run: |
          pwd
          ls -la tlaps-ci.cfg
          export TLA_PATH="$PWD/tla:$PWD/proofs"
          tlapm -C "$PWD/tlaps-ci.cfg" proofs/QuorumIntersection.tla 2>&1 | tee verification_logs/tlaps_quorum_ci.log

      - name: Prove CertificateUniqueness
        run: |
          export TLA_PATH="$PWD/tla:$PWD/proofs"
          tlapm -C "$PWD/tlaps-ci.cfg" proofs/CertificateUniqueness.tla 2>&1 | tee verification_logs/tlaps_cert_ci.log

      - name: Prove FinalizationSafety
        run: |
          export TLA_PATH="$PWD/tla:$PWD/proofs"
          tlapm -C "$PWD/tlaps-ci.cfg" proofs/FinalizationSafety.tla 2>&1 | tee verification_logs/tlaps_final_ci.log

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: closed-proofs
          path: |
            proofs/.tlacache/
            verification_logs/*.log
            tlaps-ci.cfg
          retention-days: 30
