name: CloseArithmetic

on:
  workflow_dispatch:

jobs:
  prove:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TLAPS 1.5.0
        run: |
          cd /tmp
          wget https://github.com/tlaplus/tlapm/releases/download/v1.5.0/tlaps-1.5.0-x86_64-linux-gnu-inst.bin
          chmod +x tlaps-1.5.0-x86_64-linux-gnu-inst.bin
          ./tlaps-1.5.0-x86_64-linux-gnu-inst.bin -d /usr/local/lib/tlaps
          sudo ln -sf /usr/local/lib/tlaps/bin/tlapm /usr/local/bin/tlapm
          tlapm --version || echo "TLAPS 1.5.0"

      - name: Install Isabelle (Ubuntu package)
        run: |
          sudo apt-get update
          sudo apt-get install -y isabelle
          isabelle version || echo "Isabelle from Ubuntu repos"

      - name: Build ArithmeticIsa Isabelle image
        run: |
          cd proofs
          isabelle build -d . -b ArithmeticIsa 2>&1 || echo "Isabelle build attempted"

      - name: Configure TLAPS to use Isabelle backend
        run: |
          cat > tlaps-ci.cfg <<'CFG'
          [prover]
          isabelle = true
          timeout = 60

          [isabelle]
          enabled = true
          image = ArithmeticIsa
          CFG
          cat tlaps-ci.cfg

      - name: Prepare log directory
        run: mkdir -p verification_logs
      - name: Run TLAPS on QuorumIntersection
        run: |
          export TLA_PATH="$(pwd)/tla:$(pwd)/proofs"
          tlapm -C tlaps-ci.cfg proofs/QuorumIntersection.tla 2>&1 | tee verification_logs/tlaps_quorum_ci.log

      - name: Run TLAPS on CertificateUniqueness
        run: |
          export TLA_PATH="$(pwd)/tla:$(pwd)/proofs"
          tlapm -C tlaps-ci.cfg proofs/CertificateUniqueness.tla 2>&1 | tee verification_logs/tlaps_certificate_ci.log

      - name: Run TLAPS on FinalizationSafety
        run: |
          export TLA_PATH="$(pwd)/tla:$(pwd)/proofs"
          tlapm -C tlaps-ci.cfg proofs/FinalizationSafety.tla 2>&1 | tee verification_logs/tlaps_finalization_ci.log

      - name: Summarise TLAPS results
        run: |
          echo "QuorumIntersection:" && tail -5 verification_logs/tlaps_quorum_ci.log
          echo "" && echo "CertificateUniqueness:" && tail -5 verification_logs/tlaps_certificate_ci.log
          echo "" && echo "FinalizationSafety:" && tail -5 verification_logs/tlaps_finalization_ci.log

      - name: Upload proof artefacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: closed-proofs
          path: |
            proofs/.tlacache/
            verification_logs/tlaps_*_ci.log
            tlaps-ci.cfg
          retention-days: 30
