name: CloseArithmetic

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  prove:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download TLAPS 1.6.0-pre
        run: |
          wget https://github.com/tlaplus/tlapm/releases/download/1.6.0-pre/tlapm-1.6.0-pre-x86_64-linux-gnu.tar.gz
          tar -xzf tlapm-1.6.0-pre-x86_64-linux-gnu.tar.gz
          sudo mv tlapm /usr/local/tlapm
          echo "/usr/local/tlapm/bin" >> $GITHUB_PATH

      - name: Download Isabelle 2025
        run: |
          wget https://www.cl.cam.ac.uk/research/hvg/Isabelle/dist/Isabelle2025_linux.tar.gz
          tar -xzf Isabelle2025_linux.tar.gz
          sudo mv Isabelle2025 /usr/local/Isabelle
          echo "ISABELLE_HOME=/usr/local/Isabelle" >> $GITHUB_ENV
          echo "/usr/local/Isabelle/bin" >> $GITHUB_PATH

      - name: Verify installations
        run: |
          tlapm --version
          isabelle version

      - name: Build ArithmeticIsa image
        run: |
          cd proofs
          isabelle build -d . -b -v ArithmeticIsa

      - name: Setup environment
        run: |
          mkdir -p verification_logs
          echo "ISABELLE_HOME=/usr/local/Isabelle" >> $GITHUB_ENV
          echo "TLA_PATH=$PWD/tla:$PWD/proofs" >> $GITHUB_ENV

      - name: Prove QuorumIntersection with Isabelle
        run: |
          tlapm -C --stretch 6 -I proofs -I tla proofs/QuorumIntersection.tla 2>&1 | tee verification_logs/tlaps_quorum_ci.log

      - name: Prove CertificateUniqueness with Isabelle
        run: |
          tlapm -C --stretch 6 -I proofs -I tla proofs/CertificateUniqueness.tla 2>&1 | tee verification_logs/tlaps_cert_ci.log

      - name: Prove FinalizationSafety with Isabelle
        run: |
          tlapm -C --stretch 6 -I proofs -I tla proofs/FinalizationSafety.tla 2>&1 | tee verification_logs/tlaps_final_ci.log

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: closed-proofs
          path: |
            proofs/.tlacache/
            verification_logs/*.log
          retention-days: 30
