name: CloseArithmetic

on:
  workflow_dispatch:

jobs:
  prove:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TLAPS nightly, Isabelle, and CVC5
        run: |
          sudo add-apt-repository -y ppa:tlaplus/nightly
          sudo apt-get update
          sudo apt-get install -y tlapl isabelle isabelle-2022-cvc5
          tlapm --version
          isabelle version

      - name: Build ArithmeticIsa Isabelle image
        run: |
          export ISABELLE_HOME=/usr/lib/isabelle
          export PATH="${ISABELLE_HOME}/bin:$PATH"
          cd proofs
          isabelle build -d . -v ArithmeticIsa

      - name: Configure TLAPS to use Isabelle backend
        run: |
          cat > tlaps-ci.cfg <<'CFG'
          [prover]
          isabelle = true
          timeout = 60

          [isabelle]
          enabled = true
          image = ArithmeticIsa
          CFG
          cat tlaps-ci.cfg

      - name: Prepare log directory
        run: mkdir -p verification_logs

      - name: Run TLAPS on QuorumIntersection
        run: |
          export TLA_PATH="$(pwd)/tla:$(pwd)/proofs"
          tlapm -C tlaps-ci.cfg proofs/QuorumIntersection.tla 2>&1 | tee verification_logs/tlaps_quorum_ci.log

      - name: Run TLAPS on CertificateUniqueness
        run: |
          export TLA_PATH="$(pwd)/tla:$(pwd)/proofs"
          tlapm -C tlaps-ci.cfg proofs/CertificateUniqueness.tla 2>&1 | tee verification_logs/tlaps_certificate_ci.log

      - name: Run TLAPS on FinalizationSafety
        run: |
          export TLA_PATH="$(pwd)/tla:$(pwd)/proofs"
          tlapm -C tlaps-ci.cfg proofs/FinalizationSafety.tla 2>&1 | tee verification_logs/tlaps_finalization_ci.log

      - name: Summarise TLAPS results
        run: |
          echo "QuorumIntersection:" && tail -5 verification_logs/tlaps_quorum_ci.log
          echo "" && echo "CertificateUniqueness:" && tail -5 verification_logs/tlaps_certificate_ci.log
          echo "" && echo "FinalizationSafety:" && tail -5 verification_logs/tlaps_finalization_ci.log

      - name: Upload proof artefacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: closed-proofs
          path: |
            proofs/.tlacache/
            verification_logs/tlaps_*_ci.log
            tlaps-ci.cfg
          retention-days: 30
